# Auto-generated by .github/workflows/update-formula.yml — do not edit by hand.
# Placeholder until the first arrus release is published; the workflow will
# overwrite this with the pinned version and checksums.
class Arrus < Formula
  desc "Arrus"
  homepage "https://github.com/dfontana/arrus"
  version "0.0.0"

  on_linux do
    on_intel do
      url "https://github.com/dfontana/arrus/releases/download/v0.0.0/arrus-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    bin.install "arrus"
  end

  test do
    system bin/"arrus", "--help"
  end
end
