# Auto-generated by .github/workflows/update-formula.yml — do not edit by hand.
class Arrus < Formula
  desc "Arrus"
  homepage "https://github.com/dfontana/arrus"
  version "0.1.1"

  on_linux do
    on_intel do
      url "https://github.com/dfontana/arrus/releases/download/v0.1.1/arrus-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "c1935df3b3b68eae7816904429e1d9b2a45930386b5964127bccd7e3d09623d9"
    end
  end

  def install
    bin.install "arrus"
  end

  test do
    system bin/"arrus", "--help"
  end
end
