# Auto-generated by .github/workflows/update-formula.yml — do not edit by hand.
class Epc < Formula
  desc "Epc"
  homepage "https://github.com/dfontana/epc"
  version "0.1.2"

  on_macos do
    on_arm do
      url "https://github.com/dfontana/epc/releases/download/v0.1.2/epc-aarch64-apple-darwin.tar.gz"
      sha256 "bee50218f284294879da1f84044060cae63eaca49fe55ca068df8086e711bd47"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dfontana/epc/releases/download/v0.1.2/epc-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "62a5d5e021a689cceb8f8061586402283831f868f8986a94f4c30bbee24100fa"
    end
    on_intel do
      url "https://github.com/dfontana/epc/releases/download/v0.1.2/epc-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "1a31d85b4e08544faa93ed705e5c5e545f9674cdfe931eeb06d6c0004af44a3b"
    end
  end

  def install
    bin.install "epc"
  end

  test do
    system bin/"epc", "--help"
  end
end
