# Auto-generated by .github/workflows/update-formula.yml — do not edit by hand.
class Epc < Formula
  desc "Epc"
  homepage "https://github.com/dfontana/epc"
  version "0.1.2"

  on_macos do
    on_arm do
      url "https://github.com/dfontana/epc/releases/download/v0.1.2/epc-aarch64-apple-darwin.tar.gz"
      sha256 "915c4fce969fed363e36164b6cc64329177d7532d2e8671fcaa4036dba92e12e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dfontana/epc/releases/download/v0.1.2/epc-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "0d1a12a269064beda74acbe16194a7cd215cbf2e231ba72c445b3a5605947724"
    end
    on_intel do
      url "https://github.com/dfontana/epc/releases/download/v0.1.2/epc-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "02aa413701833518be5954563ef5389c14669f94ccbdde0aacada91900094403"
    end
  end

  def install
    bin.install "epc"
  end

  test do
    system bin/"epc", "--help"
  end
end
