# Auto-generated by .github/workflows/update-formula.yml — do not edit by hand.
class Epc < Formula
  desc "Epc"
  homepage "https://github.com/dfontana/epc"
  version "0.1.1"

  on_macos do
    on_arm do
      url "https://github.com/dfontana/epc/releases/download/v0.1.1/epc-aarch64-apple-darwin.tar.gz"
      sha256 "8c11fb380a55c2a8b1af9f766921ce51800bdb1b6287bc2f9162971667ddcd3c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dfontana/epc/releases/download/v0.1.1/epc-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "d93588c157e10302a2b6f23193876572586701e4b0ef81fb8f149267cd6617fa"
    end
    on_intel do
      url "https://github.com/dfontana/epc/releases/download/v0.1.1/epc-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "df11bad51e0bfe03638581849c1d5768978467a0896244d2045dc6792a2c0ff3"
    end
  end

  def install
    bin.install "epc"
  end

  test do
    system bin/"epc", "--help"
  end
end
