# Auto-generated by .github/workflows/update-formula.yml — do not edit by hand.
class Gph < Formula
  desc "Kitty-native Mermaid previewer and SVG exporter"
  homepage "https://github.com/dfontana/gph"
  version "0.3.1"

  on_macos do
    on_arm do
      url "https://github.com/dfontana/gph/releases/download/v0.3.1/gph-aarch64-apple-darwin.tar.gz"
      sha256 "ec46bfe320d66ba79301965906a54b49e8e25cbeecca516ecea1446aab012421"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dfontana/gph/releases/download/v0.3.1/gph-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "c52a08ddaace5e38c633f9490a0860348fd6bde9121c55a182f88de4fd3421ce"
    end
    on_intel do
      url "https://github.com/dfontana/gph/releases/download/v0.3.1/gph-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "61c2db23b28a9cf70afd172826c26e3a8a605f3980e51e6c0a4b529204d5f806"
    end
  end

  def install
    bin.install "gph"
  end

  test do
    system bin/"gph", "--help"
  end
end
