# Auto-generated by .github/workflows/update-formula.yml — do not edit by hand.
class Gph < Formula
  desc "Kitty-native Mermaid previewer and SVG exporter"
  homepage "https://github.com/dfontana/gph"
  version "0.3.0"

  on_macos do
    on_arm do
      url "https://github.com/dfontana/gph/releases/download/v0.3.0/gph-aarch64-apple-darwin.tar.gz"
      sha256 "d0fb560b3bce4b6616cb9a9657ddf03b562ee0ada235b4e313ffbb2f0c21ac90"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dfontana/gph/releases/download/v0.3.0/gph-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "f9ee523818d21162d446db3eb05f90391bf553e2faac787a7fc6e31bbf7dae7e"
    end
    on_intel do
      url "https://github.com/dfontana/gph/releases/download/v0.3.0/gph-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "88c4e801053965e4b303e672bcd0f8572bc80b0c9d8864549ddbeb73502e3f6f"
    end
  end

  def install
    bin.install "gph"
  end

  test do
    system bin/"gph", "--help"
  end
end
