# Auto-generated by .github/workflows/update-formula.yml — do not edit by hand.
class Shpi < Formula
  desc "Shpi"
  homepage "https://github.com/dfontana/shpi"
  version "0.0.0"

  on_macos do
    on_arm do
      url "https://github.com/dfontana/shpi/releases/download/v0.0.0/shpi-aarch64-apple-darwin.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dfontana/shpi/releases/download/v0.0.0/shpi-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/dfontana/shpi/releases/download/v0.0.0/shpi-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    bin.install "shpi"
  end

  test do
    system bin/"shpi", "--help"
  end
end
