# Auto-generated by .github/workflows/update-formula.yml — do not edit by hand.
class Starjj < Formula
  desc "Fast jujutsu prompt segment for Starship"
  homepage "https://github.com/dfontana/starjj"
  version "0.1.2"

  on_macos do
    on_arm do
      url "https://github.com/dfontana/starjj/releases/download/v0.1.2/starjj-aarch64-apple-darwin.tar.gz"
      sha256 "b2c471409483f64841a095fd8b2206514b50f3e29a42352ee6ca8c9f807087d2"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dfontana/starjj/releases/download/v0.1.2/starjj-aarch64-unknown-linux-musl.tar.gz"
      sha256 "16fa34711f4421403c5fb0cd0c562e6f244b87137bbf3d1879dec70dc2fe7dcf"
    end
    on_intel do
      url "https://github.com/dfontana/starjj/releases/download/v0.1.2/starjj-x86_64-unknown-linux-musl.tar.gz"
      sha256 "8a013088dd7cfb2929af4c00765b4cffab1ad81ed63b9f5fb98baf5ffc5404c6"
    end
  end

  def install
    bin.install "starjj"
  end

  test do
    system bin/"starjj", "--help"
  end
end
