# Auto-generated by .github/workflows/update-formula.yml — do not edit by hand.
# Placeholder until the first starjj release is published; the workflow will
# overwrite this with the pinned version and checksums.
class Starjj < Formula
  desc "Fast jujutsu prompt segment for Starship"
  homepage "https://github.com/dfontana/starjj"
  version "0.0.0"

  on_macos do
    on_arm do
      url "https://github.com/dfontana/starjj/releases/download/v0.0.0/starjj-aarch64-apple-darwin.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dfontana/starjj/releases/download/v0.0.0/starjj-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/dfontana/starjj/releases/download/v0.0.0/starjj-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    bin.install "starjj"
  end

  test do
    system bin/"starjj", "--help"
  end
end
