# Auto-generated by .github/workflows/update-formula.yml — do not edit by hand.
class Starjj < Formula
  desc "Fast jujutsu prompt segment for Starship"
  homepage "https://github.com/dfontana/starjj"
  version "0.1.1"

  on_macos do
    on_arm do
      url "https://github.com/dfontana/starjj/releases/download/v0.1.1/starjj-aarch64-apple-darwin.tar.gz"
      sha256 "8e10e83ad5efe0de5e9bf26e26f58211d9251850a3459bcf6521b49f34bd66e4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dfontana/starjj/releases/download/v0.1.1/starjj-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "4731baa29ecbb77d705f901df3afd8c148d693bc3f3c5558bbfa2fee9cd2d6cd"
    end
    on_intel do
      url "https://github.com/dfontana/starjj/releases/download/v0.1.1/starjj-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "c99f74c94e6ea4497bf237b93bb8cec5904ed8da39a678c77963705f272b7fee"
    end
  end

  def install
    bin.install "starjj"
  end

  test do
    system bin/"starjj", "--help"
  end
end
