# Auto-generated by .github/workflows/update-formula.yml — do not edit by hand.
class Tpl < Formula
  desc "Render templated dotfiles using data sourced from a number of locations"
  homepage "https://github.com/dfontana/tpl"
  version "0.1.1"

  on_macos do
    on_arm do
      url "https://github.com/dfontana/tpl/releases/download/v0.1.1/tpl-aarch64-apple-darwin.tar.gz"
      sha256 "358191f011b56afac15e087708495cb1f09e680d30307784d37106359ed982c3"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dfontana/tpl/releases/download/v0.1.1/tpl-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "b1f89d4a5a57c49bde1f5353c7342e90c01e5d5cdbb62f9b7d7ab89fe79b8659"
    end
    on_intel do
      url "https://github.com/dfontana/tpl/releases/download/v0.1.1/tpl-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "1178e82c212378b8303b2701769c4900c4133864d0417b11663fc9a148afd5dd"
    end
  end

  def install
    bin.install "tpl"
  end

  test do
    system bin/"tpl", "--help"
  end
end
