# Auto-generated by .github/workflows/update-formula.yml — do not edit by hand.
# Placeholder until the first tpl release is published; the workflow will
# overwrite this with the pinned version and checksums.
class Tpl < Formula
  desc "Render templated dotfiles using data sourced from a number of locations"
  homepage "https://github.com/dfontana/tpl"
  version "0.0.0"

  on_macos do
    on_arm do
      url "https://github.com/dfontana/tpl/releases/download/v0.0.0/tpl-aarch64-apple-darwin.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/dfontana/tpl/releases/download/v0.0.0/tpl-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/dfontana/tpl/releases/download/v0.0.0/tpl-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    bin.install "tpl"
  end

  test do
    system bin/"tpl", "--help"
  end
end
