#!/usr/bin/env bash
#
# Regenerate Formula/arrus.rb pinned to an arrus release.
#
# Usage: scripts/gen-arrus-formula.sh [tag]
#   tag  release tag to pin (e.g. v0.1.1). Defaults to the latest release.
#
# Requires: gh (authenticated), sha256sum. Exits 0 (no-op) if no release exists.
set -euo pipefail

REPO="dfontana/arrus"
FORMULA="Formula/arrus.rb"

tag="${1:-}"
if [ -z "$tag" ]; then
  tag="$(gh release view --repo "$REPO" --json tagName -q .tagName 2>/dev/null || true)"
fi
if [ -z "$tag" ]; then
  echo "No arrus release found yet; leaving $FORMULA untouched."
  exit 0
fi

version="${tag#v}"
base="https://github.com/$REPO/releases/download/$tag"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

sha() {
  local asset="arrus-$1.tar.gz"
  gh release download "$tag" --repo "$REPO" --pattern "$asset" --dir "$tmp" --clobber
  sha256sum "$tmp/$asset" | cut -d' ' -f1
}

sha_linux_x86="$(sha x86_64-unknown-linux-gnu)"

echo "Pinning arrus $version ($tag)"

cat > "$FORMULA" <<EOF
# Auto-generated by .github/workflows/update-formula.yml — do not edit by hand.
class Arrus < Formula
  desc "Arrus"
  homepage "https://github.com/$REPO"
  version "$version"

  on_linux do
    on_intel do
      url "$base/arrus-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "$sha_linux_x86"
    end
  end

  def install
    bin.install "arrus"
  end

  test do
    system bin/"arrus", "--help"
  end
end
EOF

echo "Wrote $FORMULA"
