#!/usr/bin/env bash
#
# Regenerate Formula/gph.rb pinned to a gph release.
#
# Usage: scripts/gen-gph-formula.sh [tag]
#   tag  release tag to pin (e.g. v0.1.1). Defaults to the latest release.
#
# Requires: gh (authenticated), sha256sum. Exits 0 (no-op) if no release exists.
set -euo pipefail

REPO="dfontana/gph"
FORMULA="Formula/gph.rb"

tag="${1:-}"
if [ -z "$tag" ]; then
  tag="$(gh release view --repo "$REPO" --json tagName -q .tagName 2>/dev/null || true)"
fi
if [ -z "$tag" ]; then
  echo "No gph release found yet; leaving $FORMULA untouched."
  exit 0
fi

version="${tag#v}"
base="https://github.com/$REPO/releases/download/$tag"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

sha() {
  local asset="gph-$1.tar.gz"
  gh release download "$tag" --repo "$REPO" --pattern "$asset" --dir "$tmp" --clobber
  sha256sum "$tmp/$asset" | cut -d' ' -f1
}

sha_macos_arm="$(sha aarch64-apple-darwin)"
sha_linux_arm="$(sha aarch64-unknown-linux-gnu)"
sha_linux_x86="$(sha x86_64-unknown-linux-gnu)"

echo "Pinning gph $version ($tag)"

cat > "$FORMULA" <<EOF
# Auto-generated by .github/workflows/update-formula.yml — do not edit by hand.
class Gph < Formula
  desc "Kitty-native Mermaid previewer and SVG exporter"
  homepage "https://github.com/$REPO"
  version "$version"

  on_macos do
    on_arm do
      url "$base/gph-aarch64-apple-darwin.tar.gz"
      sha256 "$sha_macos_arm"
    end
  end

  on_linux do
    on_arm do
      url "$base/gph-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "$sha_linux_arm"
    end
    on_intel do
      url "$base/gph-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "$sha_linux_x86"
    end
  end

  def install
    bin.install "gph"
  end

  test do
    system bin/"gph", "--help"
  end
end
EOF

echo "Wrote $FORMULA"
